package tools

func (h *Host) build() (*Registry, error) {
	ro := FlagReadOnly | FlagIdempotent
	return NewRegistry(
		Tool{Name: "list_vaults", Description: "List vaults accessible to this API key.",
			Flags: ro, Input: listVaultsIn{}, Output: listVaultsOut{}, Handler: Typed(h.listVaults)},
		Tool{Name: "list_notes", Description: "List notes in a vault (metadata only by default; path matches Obsidian). Use folder to filter by top folder.",
			Flags: ro, Input: listNotesIn{}, Output: listNotesOut{}, Handler: Typed(h.listNotes)},
		Tool{Name: "read_note", Description: "Read one note: content, mtime, size, and contentHash. Use contentHash as baseHash when writing back.",
			Flags: ro, Input: readNoteIn{}, Output: readNoteOut{}, Handler: Typed(h.readNote)},
		Tool{Name: "search_notes", Description: "Search notes by keyword (case-insensitive substring over path and content). Returns path + snippet.",
			Flags: ro, Input: searchNotesIn{}, Output: searchNotesOut{}, Handler: Typed(h.searchNotes)},
		Tool{Name: "write_note", Description: "Create or update a note (upsert). Pass baseHash from your last read to avoid overwriting concurrent edits; on conflict, re-read and merge, or force=true to overwrite.",
			Input: writeNoteIn{}, Output: writeNoteOut{}, Handler: Typed(h.writeNote)},
		Tool{Name: "append_note", Description: "Append text to the end of a note. Safer than read-modify-write for logs and diaries: concurrent edits are merged, not lost.",
			Input: appendNoteIn{}, Output: appendNoteOut{}, Handler: Typed(h.appendNote)},
		Tool{Name: "rename_note", Description: "Rename or move a note.",
			Input: renameNoteIn{}, Output: renameNoteOut{}, Handler: Typed(h.renameNote)},
		Tool{Name: "delete_note", Description: "Delete a note (also deletes the local file on synced Obsidian clients). Destructive: requires confirm=path.",
			Flags: FlagDestructive, Input: deleteNoteIn{}, Output: deleteNoteOut{}, Handler: Typed(h.deleteNote)},
		Tool{Name: "list_tags", Description: "List all #tags in a vault with occurrence counts.",
			Flags: ro, Input: listTagsIn{}, Output: listTagsOut{}, Handler: Typed(h.listTags)},
		Tool{Name: "find_by_tag", Description: "Find notes that contain a given #tag.",
			Flags: ro, Input: findByTagIn{}, Output: findByTagOut{}, Handler: Typed(h.findByTag)},
		Tool{Name: "get_outlinks", Description: "List [[wikilink]] targets that a note points to.",
			Flags: ro, Input: linksIn{}, Output: linksOut{}, Handler: Typed(h.getOutlinks)},
		Tool{Name: "get_backlinks", Description: "List notes that [[wikilink]] to the given note.",
			Flags: ro, Input: linksIn{}, Output: linksOut{}, Handler: Typed(h.getBacklinks)},
		Tool{Name: "find_broken_links", Description: "Find [[wikilink]]s that point to notes that do not exist.",
			Flags: ro, Input: findBrokenIn{}, Output: findBrokenOut{}, Handler: Typed(h.findBrokenLinks)},
		Tool{Name: "find_orphans", Description: "Find notes with no incoming [[wikilink]]s (orphans). Useful for cleanup.",
			Flags: ro, Input: findOrphansIn{}, Output: findOrphansOut{}, Handler: Typed(h.findOrphans)},
		Tool{Name: "get_vault_stats", Description: "Vault overview: note count, size, folder distribution, recently modified notes.",
			Flags: ro, Input: vaultStatsIn{}, Output: vaultStatsOut{}, Handler: Typed(h.getVaultStats)},
		Tool{Name: "get_recent_changes", Description: "List recent sync activity (creates, updates, deletes, merges, conflicts) for a vault.",
			Flags: ro, Input: recentChangesIn{}, Output: recentChangesOut{}, Handler: Typed(h.getRecentChanges)},
		Tool{Name: "list_devices", Description: "List devices that have connected to a vault, with online status.",
			Flags: ro, Input: listDevicesIn{}, Output: listDevicesOut{}, Handler: Typed(h.listDevices)},
		Tool{Name: "get_server_info", Description: "Server version and number of currently connected Obsidian clients.",
			Flags: ro, Input: serverInfoIn{}, Output: serverInfoOut{}, Handler: Typed(h.getServerInfo)},
		Tool{Name: "get_share", Description: "Get the public-share status of a note (token + /share/<token> URL if enabled).",
			Flags: ro, Input: getShareIn{}, Output: getShareOut{}, Handler: Typed(h.getShare)},
		Tool{Name: "read_attachment", Description: "Read an image/PDF attachment as binary content (returned as an image/blob content block for multimodal clients).",
			Flags: ro, Input: readAttachmentIn{}, Handler: Typed(h.readAttachment)},
		Tool{Name: "set_share", Description: "Enable or disable public sharing for a note. Token is stable across toggles.",
			Input: setShareIn{}, Output: setShareOut{}, Handler: Typed(h.setShare)},
	)
}
